# Generated by Django 2.0.5 on 2019-08-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='thumbail_url',
            new_name='thumbnail',
        ),
    ]
