# Generated by Django 2.0.5 on 2019-08-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_thumbnail_rename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='scraper.Categories'),
        ),
        migrations.AlterField(
            model_name='books',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
