# Generated by Django 2.0.5 on 2019-08-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190821_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='product_description',
        ),
    ]
