# Generated by Django 2.0.5 on 2019-08-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20190821_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='product_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
